#!/usr/bin/env bash
# Source file: util/ccnd-autoconfig.sh
#
# Script that tries to (automatically) discover of a local ccnd gateway
#
# Part of the CCNx distribution.
#
# Copyright (C) 2012 Palo Alto Research Center, Inc.
#           (c) 2013 University of California, Los Angeles
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# This script should be installed in the same place as ccnd, ccndc, ccndsmoketest, ...
# adjust the path to get consistency.
D=`dirname "$0"`
export PATH="$D:$PATH"

DIG=${DIR:-"/usr/bin/dig"}

function do-need-to-reconfig {
    face=`ccndstatus | grep "ccnx:/autoconf-route face" | awk '{print $3}'`
    if [ "x$face" == "x" ]; then
        return 0
    else
        return 1
    fi
}

function run-autoconfig {
    ccndstatus | grep 224.0.23.170:59695 > /dev/null
    MCAST_EXISTED=$?

    # Removing any previously created (either by this script or ccndc srv command) default route
    for i in `ccndstatus | grep "ccnx:/autoconf-route face" | awk '{print $3}'`; do
       ccndc del / face $i
       ccndc del /autoconf-route face $i
    done

    # Set temporary multicast face
    ccndc -t 10 add "/local/ndn" udp  224.0.23.170 59695

    ###########################################################
    # Part one. Auto-discovery of ccnd in the same subnetwork #
    ###########################################################

    # Get info from local hub, if available
    info=`ccnpeek -w 1 -vs 2 -c /local/ndn/udp 2>/dev/null` # wait at most 1 second
    if [ "x$info" = "x" ]; then
       echo "Part one failed: local hub is not availble, trying to use DNS to get local configuration"

       ##############################################
       # Part two. Fallback configuration using DNS #
       ##############################################

       # Don't use "ccndc srv", because we need to remember the created automatic route
       info=`$DIG +search +short +cmd +tries=2 +ndots=10 _ccnx._udp srv | head -1 | awk '{print $4,$3}'`
       if [ "x$info" = "x" ]; then
           echo "Part two failed: DNS query for _ccnx._udp srv returned nothing, trying part three"

           PUBKEY_NAME=`ndn-pubkey-name`

           if [ -z "$PUBKEY_NAME" ]; then
               echo "ERROR: Part three failed: public key name is not configured"
               echo "Refer to ``man ccnd-autconfig''  for more information about how to set up public key name"
               return 1
           fi

           DNS_QUERY="_ccnx._udp.`ndn-name-dnsifier.py -r 1 -l 2 "$PUBKEY_NAME"`._homehub._autoconf.named-data.net"

           info=`$DIG +search +short +cmd +tries=2 +ndots=10 "$DNS_QUERY" srv | head -1 | awk '{print $4,$3}'`
           if [ "x$info" = "x" ]; then
               echo "ERROR: Part three failed: DNS query for "$DNS_QUERY" srv returned nothing"
               return 1
           else
               echo "OK: part three succeeded: $info"
           fi
       else
           echo "OK: part two succeeded: $info"
       fi
    else
        echo "OK: part one succeded: $info"
    fi

    echo Setting default route to a local hub: "$info"
    echo "$info" | xargs ccndc add / udp
    echo "$info" | xargs ccndc add /autoconf-route udp

    if [ $MCAST_EXISTED -eq 1 ]; then
       # destroying multicast face
       ccndstatus | grep 224.0.23.170:59695 | awk '{print $2}' | xargs ccndc destroy face
    fi
}

if [ "x$1" == "x-d" ]; then
    run-autoconfig

    PID=${2:-"/var/run/ccnd-autoconfig.pid"}
    if test -f $PID &&  ps -p `cat $PID` >&-; then
        # No need to run daemon, as it is already running
        exit 0
    fi

    echo $$ > $PID

    # Infinite loop with reconfig every 5 minutes
    while true; do
        if do-need-to-reconfig; then
            echo "Trying to reconfigure automatic route..."
            run-autoconfig
        fi
        sleep 10
    done
else
    run-autoconfig
    exit $?
fi

