ndn_ndnbtoxml.1.html: ndn_ndnbtoxml.1.txt
ndn_xmltondnb.1.html: ndn_xmltondnb.1.txt
ndnacl.1.html: ndnacl.1.txt
ndngroup.1.html: ndngroup.1.txt
ndnc.1.html: ndnc.1.txt
ndnd.1.html: ndnd.1.txt
ndndc.1.html: ndndc.1.txt
ndndcontrol.1.html: ndndcontrol.1.txt
ndndlogging.1.html: ndndlogging.1.txt
ndndsmoketest.1.html: ndndsmoketest.1.txt
ndndstart.1.html: ndndstart.1.txt
ndndstatus.1.html: ndndstatus.1.txt
ndndstop.1.html: ndndstop.1.txt
ndnexplore.1.html: ndnexplore.1.txt
ndnls.1.html: ndnls.1.txt
ndnlsrepo.1.html: ndnlsrepo.1.txt
ndngetfile.1.html: ndngetfile.1.txt
ndnputfile.1.html: ndnputfile.1.txt
ndnputmeta.1.html: ndnputmeta.1.txt
ndngetmeta.1.html: ndngetmeta.1.txt
ndnlibtest.1.html: ndnlibtest.1.txt
ndnnamelist.1.html: ndnnamelist.1.txt
ndnrm.1.html: ndnrm.1.txt
ndnseqwriter.1.html: ndnseqwriter.1.txt
ndn_repo.1.html: ndn_repo.1.txt
ndncat.1.html: ndncat.1.txt
ndnslurp.1.html: ndnslurp.1.txt
ndnchat.1.html: ndnchat.1.txt
ndnpeek.1.html: ndnpeek.1.txt
ndnpoke.1.html: ndnpoke.1.txt
ndnr.1.html: ndnr.1.txt
ndnsyncslice.1.html: ndnsyncslice.1.txt
ndnsyncwatch.1.html: ndnsyncwatch.1.txt
ndnlink.1.html: ndnlink.1.txt
ndnprintlink.1.html: ndnprintlink.1.txt
ndnrepoimport.1.html: ndnrepoimport.1.txt
ndntestloop.1.html: ndntestloop.1.txt
ndn_ndnbtoxml.1.pdf: ndn_ndnbtoxml.1.txt
ndn_xmltondnb.1.pdf: ndn_xmltondnb.1.txt
ndnacl.1.pdf: ndnacl.1.txt
ndngroup.1.pdf: ndngroup.1.txt
ndnc.1.pdf: ndnc.1.txt
ndnd.1.pdf: ndnd.1.txt
ndndc.1.pdf: ndndc.1.txt
ndndcontrol.1.pdf: ndndcontrol.1.txt
ndndlogging.1.pdf: ndndlogging.1.txt
ndndsmoketest.1.pdf: ndndsmoketest.1.txt
ndndstart.1.pdf: ndndstart.1.txt
ndndstatus.1.pdf: ndndstatus.1.txt
ndndstop.1.pdf: ndndstop.1.txt
ndnexplore.1.pdf: ndnexplore.1.txt
ndnls.1.pdf: ndnls.1.txt
ndnlsrepo.1.pdf: ndnlsrepo.1.txt
ndngetfile.1.pdf: ndngetfile.1.txt
ndnputfile.1.pdf: ndnputfile.1.txt
ndnputmeta.1.pdf: ndnputmeta.1.txt
ndngetmeta.1.pdf: ndngetmeta.1.txt
ndnlibtest.1.pdf: ndnlibtest.1.txt
ndnnamelist.1.pdf: ndnnamelist.1.txt
ndnrm.1.pdf: ndnrm.1.txt
ndnseqwriter.1.pdf: ndnseqwriter.1.txt
ndn_repo.1.pdf: ndn_repo.1.txt
ndncat.1.pdf: ndncat.1.txt
ndnslurp.1.pdf: ndnslurp.1.txt
ndnchat.1.pdf: ndnchat.1.txt
ndnpeek.1.pdf: ndnpeek.1.txt
ndnpoke.1.pdf: ndnpoke.1.txt
ndnr.1.pdf: ndnr.1.txt
ndnsyncslice.1.pdf: ndnsyncslice.1.txt
ndnsyncwatch.1.pdf: ndnsyncwatch.1.txt
ndnlink.1.pdf: ndnlink.1.txt
ndnprintlink.1.pdf: ndnprintlink.1.txt
ndnrepoimport.1.pdf: ndnrepoimport.1.txt
ndntestloop.1.pdf: ndntestloop.1.txt
ndn_ndnbtoxml.1: ndn_ndnbtoxml.1.txt
ndn_xmltondnb.1: ndn_xmltondnb.1.txt
ndnacl.1: ndnacl.1.txt
ndngroup.1: ndngroup.1.txt
ndnc.1: ndnc.1.txt
ndnd.1: ndnd.1.txt
ndndc.1: ndndc.1.txt
ndndcontrol.1: ndndcontrol.1.txt
ndndlogging.1: ndndlogging.1.txt
ndndsmoketest.1: ndndsmoketest.1.txt
ndndstart.1: ndndstart.1.txt
ndndstatus.1: ndndstatus.1.txt
ndndstop.1: ndndstop.1.txt
ndnexplore.1: ndnexplore.1.txt
ndnls.1: ndnls.1.txt
ndnlsrepo.1: ndnlsrepo.1.txt
ndngetfile.1: ndngetfile.1.txt
ndnputfile.1: ndnputfile.1.txt
ndnputmeta.1: ndnputmeta.1.txt
ndngetmeta.1: ndngetmeta.1.txt
ndnlibtest.1: ndnlibtest.1.txt
ndnnamelist.1: ndnnamelist.1.txt
ndnrm.1: ndnrm.1.txt
ndnseqwriter.1: ndnseqwriter.1.txt
ndn_repo.1: ndn_repo.1.txt
ndncat.1: ndncat.1.txt
ndnslurp.1: ndnslurp.1.txt
ndnchat.1: ndnchat.1.txt
ndnpeek.1: ndnpeek.1.txt
ndnpoke.1: ndnpoke.1.txt
ndnr.1: ndnr.1.txt
ndnsyncslice.1: ndnsyncslice.1.txt
ndnsyncwatch.1: ndnsyncwatch.1.txt
ndnlink.1: ndnlink.1.txt
ndnprintlink.1: ndnprintlink.1.txt
ndnrepoimport.1: ndnrepoimport.1.txt
ndntestloop.1: ndntestloop.1.txt
