'\" t
.\"     Title: ndnd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.2
.\"  Language: English
.\"
.TH "NDND" "1" "05/16/2013" "\ \& 0\&.7\&.2" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ndnd \- NDNx Daemon
.SH "SYNOPSIS"
.sp
\fBndnd\fR [\-h]
.SH "DESCRIPTION"
.sp
\fBndnd\fR is not normally executed directly\&. Use \fBndndstart(1)\fR to run an instance of ndnd\&. \fBndnd\fR normally runs indefinitely\&. Use \fBndndsmoketest(1)\fR to terminate a \fBndnd\fR (or use \fBkill(1)\fR)\&.
.sp
\fBndnd\fR is the software forwarder/router for NDNx and is required for normal NDNx protocol communication\&. The typical configuration is to run one \fBndnd\fR on each host; applications running on the host will communicate through the local \fBndnd\fR, and it will communicate over attached networks (directly or through a link adapter process)\&.
.sp
\fBndnd\fR takes no options on the command\-line\&. Basic options are controlled by environment variables\&. The forwarding table (FIB) is populated with registration protocols over NDNx\&. Use \fBndndc(1)\fR for configuring the FIB\&.
.sp
\fBndnd\fR communicates via the NDNx protocol running over UDP, TCP, or Unix domain sockets (the latter for local processes only)\&. It also provides a simple web status view over HTTP, on the NDN_LOCAL_PORT\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Print a usage message describing environment variables\&.
.RE
.SH "ENVIRONMENT"
.sp
Options for \fBndnd\fR are set via environment variables\&.
.sp
.if n \{\
.RS 4
.\}
.nf
NDND_DEBUG=
  0 \- no messages
  1 \- basic messages (any non\-zero value gets these)
  2 \- interest messages
  4 \- content messages
  8 \- matching details
  16 \- interest details
  32 \- gory interest details
  64 \- log occasional human\-readable timestamps
  128 \- face registration debugging
  bitwise OR these together for combinations; \-1 gets max logging
NDN_LOCAL_PORT=
  UDP port for unicast clients (default 9695)\&.
  Also listens on this TCP port for stream connections\&.
  Also affects name of unix\-domain socket\&.
NDN_LOCAL_SOCKNAME=
  Name stem of unix\-domain socket (default /tmp/\&.ndnd\&.sock)\&.
NDND_CAP=
  Capacity limit, in count of ContentObjects\&.
  Not an absolute limit\&.
NDND_MTU=
  Packet size in bytes\&.
  If set, interest stuffing is allowed within this budget\&.
  Single items larger than this are not precluded\&.
NDND_DATA_PAUSE_MICROSEC=
  Adjusts content\-send delay time for multicast and udplink faces
NDND_DEFAULT_TIME_TO_STALE=
  Default for content objects without explicit FreshnessSeconds,
  in seconds\&.  Must be positive\&.
NDND_MAX_TIME_TO_STALE=
  Limit, in seconds, until content becomes stale\&.  Must be positive\&.
  If necessary, this will be reduced to the largest value
  that the implemementation can enforce\&.
NDND_MAX_RTE_MICROSEC=
  Value used to limit response time estimates kept by default strategy\&.
NDND_KEYSTORE_DIRECTORY=
  Directory readable only by ndnd where its keystores are kept
  Defaults to a private subdirectory of /var/tmp
NDND_LISTEN_ON=
  List of ip addresses to listen on; defaults to wildcard\&. The
  addresses may be enclosed in square brackets\&.  The list elements
  are separated by whitespace, commas, or semicolons\&.  Both IPv4 and
  IPv6 addresses may be used\&.  Set this if you want to limit
  connectivity to a particular set of configured addresses\&.
  The most useful non\-default setting is probably "localhost"\&.
  Note that outgoing tcp connections may still be made\&.
NDND_AUTOREG=
  List of prefixes to auto\-register on new faces initiated by peers\&.
  The prefixes are represented as ndnx URIs, and
  are separated by whitespace, commas, or semicolons\&.
  If this is specified, the ndnd can be used as a "hub" to forward
  interests matching these prefixes to any peer that talks to it\&.
  example: NDND_AUTOREG=ndn:/ndnx\&.org/Users,ndn:/ndnx\&.org/Chat
NDND_PREFIX=
  A prefix stem to use for generating guest prefixes\&.
.fi
.if n \{\
.RE
.\}
.SH "NAME SPACES"
.sp
After \fBndnd\fR starts, control of its behavior takes place using NDNx protocols\&. For more information, please refer to NameConventions int the technical documentation\&.
.sp
This is where ndnd publishes its key, using the service discovery profile:
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/%C1\&.M\&.S\&.localhost/%C1\&.M\&.SRV/ndnd
.fi
.if n \{\
.RE
.\}
.sp
For the benefit of neighboring nodes, the key is published here as well:
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/%C1\&.M\&.S\&.neighborhood/%C1\&.M\&.SRV/ndnd
.fi
.if n \{\
.RE
.\}
.sp
The following is the main prefix used to communicate with this instance of ndnd\&. Here <ndndid> refers to the SHA256 digest of the ndnd\(cqs public key\&. Note that, for historical reasons, this does not use the key marker convention\&. Each instance of ndnd may be assumed to be using a distict public key\&. See Registration for a description of the protocols used in in this namespace\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/ndnx/<ndndid>
.fi
.if n \{\
.RE
.\}
.sp
A stream of face status changes may be obtained through the the name below\&. This uses the standard versioning and segmentation profiles, so a utility such as \fBndncat\fR may be used to read it\&. At present, only one version of the stream is started when it is requested for the first time, so a program that needs to access it should start shortly after \fBndnd\fR and run as long as the \fBndnd\fR instance is around\&. The format of this stream is a simple text\-based one\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/ndnx/<ndndid>/notice\&.txt
.fi
.if n \{\
.RE
.\}
.sp
When two ndnds begin exchanging interest and data, an automatic handshake takes place to agree upon a name prefix that both nodes can use to refer to the communication channel\&. This prefix is registered on each node to forward interests to the other\&. An example of such a prefix is
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/%C1\&.M\&.FACE/%C1\&.M\&.G%00%00XL%DB%F0%0A%0APn%0F%B1%F2%1F
.fi
.if n \{\
.RE
.\}
.sp
The first name component is always the same\&. The second component is a randomly\-generated guid, with a guid marker\&. (These guids are abbreviated below to make them easier to read\&.)
.sp
As a byproduct of this handshake, each ndnd creates a content object that represents its endpoint\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
ndn:/%C1\&.M\&.FACE/%C1\&.M\&.G%00%00XL42/%C1\&.M\&.NODE/%C1\&.M\&.K%00\&.\&.\&.1/face~7/%FD\&.\&.\&.
ndn:/%C1\&.M\&.FACE/%C1\&.M\&.G%00%00XL42/%C1\&.M\&.NODE/%C1\&.M\&.K%00\&.\&.\&.2/face~9/%FD\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
The third component is the constant %C1\&.M\&.NODE, to allow the remainder if the namespace to be used for other purposes\&. The fourth component is the ndndid, with the key digest marker\&. These have been abbreviated in the example\&. The fifth component is the faceid, in decimal ascii, with a leading distinguisher of \fIface~\fR\&. The remaining two components are for standard versioning and segmentation\&.
.sp
Currently there is no payload in these content objects\&. This is subject to change\&.
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error)
.RE
.SH "AUTHOR"
.sp
Michael Plass
