#!/bin/sh
# csrc/makeagentcov
# Assuming we're using gcc, set up to run gcov on ndnd.
# 
# Part of the NDNx distribution.
#
# Portions Copyright (C) 2013 Regents of the University of California.
# 
# Based on the CCNx C Library by PARC.
# Copyright (C) 2009 Palo Alto Research Center, Inc.
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
./configure && make clean && make
rm ndnd/ndnd.o ndnd/ndnd lib/ndn_match.o
make CFLAGS='-g -fprofile-arcs -ftest-coverage' SUBDIRS='lib ndnd'
echo "### Say 'make coverage' after test run to generate gcov results"
